Badges
ostbob/test-guru pull request #18
Opened 2021-08-10 13:44 UTC by ostbob

Разработан функционал, который позволит пользователям получать бэйджи (награды) за успешное прохождение тестов.
1) Бэйджи представляются моделью Badge
2) Пользователь может получать один и тот же бэйдж более одного раза
3) Бэйдж обязательно содержит атрибуты:
      Название
      Имя файла с изображением 
4) Выдача бэйджов происходит автоматически после завершения теста
5) Управление бэйджами осуществляется администратором
6) При создании бэйджа администратор также назначает правило которое определяет порядок выдачи бэйджа. 
    Примеры правил:
      Выдать бэйдж после успешного прохождения всех тестов из категории Backend
      Выдать бэйдж после успешного прохождения теста с первой попытки
      Выдать бэйдж после успешного прохождения всех тестов определённого уровня
    Допускается что критерии правил заданы заранее, например на уровне атрибутов модели
7) Пользователь в любой момент времени может посмотреть список всех существующих и заработанных бэйджей

2021-08-10 19:05 UTC, BubuntuClu requested changes

2021-08-10 19:05 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +  before_action :set_badges, only: %i[index]
зачем ради одного экшена делать колбэк?

```
def index
   @user_badges = current_user.badges
   @badges = Badge.all
end
```
чем плохо?

2021-08-10 19:05 UTC, BubuntuClu commented on app/controllers/admin/badges_controller.rb
> +  before_action :set_badges, only: %i[index]
тем более что тут https://github.com/ostbob/test-guru/pull/18/files#diff-6c5b8b18f125c230a2df754efaa1551bb1233689a90fe6511c26a7b280d3d440R4 ты так и сделал)

2021-08-10 19:05 UTC, BubuntuClu commented on app/controllers/badges_controller.rb
> +    def set_badge
а нужен ли этот метод? 
может?
```
def show
  @badge = Badge.find(params[:id])
end
```

2021-08-10 19:05 UTC, BubuntuClu commented on db/migrate/20210810083443_add_value_to_badges.rb
> +class AddValueToBadges < ActiveRecord::Migration[5.2]
ну ты ведь локально делаешь, видишь что забыл поле сделать, откати создание таблицы и добавь туда поле, зачем "лишнюю" миграцию для этого делать?

откати ее и поправь миграцию создания бейджей

2021-08-10 19:05 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +        @test_passage.update_attribute(:success_flg, true)
success_flg )))
много места сэкономил не добавив `a`?)

на мой взгляд, тут достаточно просто `success`

2021-08-10 19:05 UTC, BubuntuClu commented on app/services/badge_issuer_service.rb
> +    category_tests_count = Test.joins("INNER JOIN categories ON tests.category_id = categories.id")
у тебя
1 - есть ассоциация для категории, чтобы не писать `joins` руками
2 - есть метод, который возвращает тесты по имени категории, почему бы его не использовать?

2021-08-10 19:05 UTC, BubuntuClu commented on app/services/badge_issuer_service.rb
> +    category_test_passages_count = TestPassage.joins("INNER JOIN tests ON tests.id = test_passages.test_id
тоже самое про использование ассоциаций в джойнах

2021-08-10 19:05 UTC, BubuntuClu commented on app/services/badge_issuer_service.rb
> +    level_test_passages_count = TestPassage.joins("INNER JOIN tests ON tests.id = test_passages.test_id")
так же есть метод, который возвращает тесты по уровню

2021-08-12 10:39 UTC, ostbob commented on app/services/badge_issuer_service.rb
> +    level_test_passages_count = TestPassage.joins("INNER JOIN tests ON tests.id = test_passages.test_id")
Поправил в 4м коммите

2021-08-12 10:39 UTC, ostbob commented on app/services/badge_issuer_service.rb
> +    category_test_passages_count = TestPassage.joins("INNER JOIN tests ON tests.id = test_passages.test_id
Поправил в 4м коммите

2021-08-12 10:39 UTC, ostbob commented on app/services/badge_issuer_service.rb
> +    category_tests_count = Test.joins("INNER JOIN categories ON tests.category_id = categories.id")
Поправил в 4м коммите

2021-08-12 10:39 UTC, ostbob commented on app/controllers/test_passages_controller.rb
> +        @test_passage.update_attribute(:success_flg, true)
Поправил в 4м коммите

2021-08-12 10:39 UTC, ostbob commented on db/migrate/20210810083443_add_value_to_badges.rb
> +class AddValueToBadges < ActiveRecord::Migration[5.2]
Поправил в 4м коммите

2021-08-12 10:39 UTC, ostbob commented on app/controllers/badges_controller.rb
> +    def set_badge
Поправил в 4м коммите

2021-08-12 10:39 UTC, ostbob commented on app/controllers/admin/badges_controller.rb
> +  before_action :set_badges, only: %i[index]
Поправил в 4м коммите

2021-08-12 17:29 UTC, merged