Added scope methods and model validations
ostbob/test-guru pull request #6
Opened 2021-04-09 12:47 UTC by ostbob

2021-04-09 20:21 UTC, BubuntuClu requested changes

2021-04-09 20:21 UTC, BubuntuClu commented on app/models/question.rb
> +    errors.add(:self, 'Question must have only 1-4 answers') if not (1..4).include?(answers.count)
`if not ` такое работает в руби?

и валидация в моделе вопросов тебе не поможет. ты когда сохраняешь ответ, у тебя вопрос не валидируется. надо перенести это в модель ответов

2021-04-09 20:21 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2021-04-09 20:21 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where(categories: {title: category}).order(title: :desc).pluck(:title) }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2021-04-09 23:23 UTC, ostbob commented on app/models/question.rb
> +    errors.add(:self, 'Question must have only 1-4 answers') if not (1..4).include?(answers.count)
1) Вроде работает:
irb(main):004:0> puts 'rabotaet' if not false
rabotaet
2) Перенёс.

2021-04-09 23:23 UTC, ostbob commented on app/models/test.rb
> +  validates :title, uniqueness: { scope: :level }
Добавил

2021-04-09 23:23 UTC, ostbob commented on app/models/test.rb
> +  scope :by_category, -> (category) { joins(:category).where(categories: {title: category}).order(title: :desc).pluck(:title) }
Исправил

2021-04-10 06:26 UTC, BubuntuClu approved these changes

2021-04-10 06:26 UTC, BubuntuClu commented on app/models/answer.rb
> +    errors.add(:self, 'Question must have only 1-4 answers') if not (1..3).include?(question.answers.count)
Забавно выглядит надпись)
Но все же лучше заменить на !if или unless.

2021-04-10 08:26 UTC, ostbob commented on app/models/answer.rb
> +    errors.add(:self, 'Question must have only 1-4 answers') if not (1..3).include?(question.answers.count)
Ок. Заменил.
Как по мне так без разницы :)

2021-04-10 08:27 UTC, merged